-- Update departments for all designations
UPDATE designations SET department = 'CSBD' WHERE title = 'Sr. Executive - Client Servicing';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Sr. Conversation Specialist';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Delegate Acquisition Specialist';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'SEO Analyst';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Conversation Specialist';
UPDATE designations SET department = 'Digicom' WHERE title = 'Web & Graphic Designer';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Executive - Lead Generation';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Sr. Manaager Database';
UPDATE designations SET department = 'Livecom' WHERE title = 'Sr. Manager - Operations';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'Partnership Development Lead';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Sr. Delegate Acquisition Specialist';
UPDATE designations SET department = 'CSBD' WHERE title = 'Sr. Account Manager';
UPDATE designations SET department = 'Digicom' WHERE title = 'Asst. Manager/3D Artist';
UPDATE designations SET department = 'CSBD' WHERE title = 'Sr. Executive Client Servicing';
UPDATE designations SET department = 'Livecom' WHERE title = 'Head of Opeartion North & East India';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Executive - Database';
UPDATE designations SET department = 'Digicom' WHERE title = 'Video Editor / VFX Artist';
UPDATE designations SET department = 'Livecom' WHERE title = 'Field Executive';
UPDATE designations SET department = 'Human Resource' WHERE title = 'Sr. Manager HR & Admin';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Sr. Team Leader – DemandCOM';
UPDATE designations SET department = 'Accounts' WHERE title = 'Accounts Assistant - Receivable';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Head – DemandCOM  Data Solution';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Asst. Team Leader – Data Research';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Data Research Associate';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Data Analyst';
UPDATE designations SET department = 'CSBD' WHERE title = 'Key Account Director';
UPDATE designations SET department = 'Livecom' WHERE title = 'Asst. Manager Operation';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Database Associate';
UPDATE designations SET department = 'Accounts' WHERE title = 'Manager - Accounts';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Asst. Manager DB';
UPDATE designations SET department = 'CSBD' WHERE title = 'Sr. Executive - Client Servicing';
UPDATE designations SET department = 'Digicom' WHERE title = 'Content & Copy Writer';
UPDATE designations SET department = 'Digicom' WHERE title = 'Sr. Manager DigiCom';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Sr. Team Leader – Data Research';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'Sr. Assistant Editor';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Sr. Conversion Specialist';
UPDATE designations SET department = 'Digicom' WHERE title = 'Web Designer';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'Assistant Editor';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Asst. Team Leader - DemandCOM';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'Marketing Executive- Alliances';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Data Validation Executive';
UPDATE designations SET department = 'CSBD' WHERE title = 'Executive – Client Servicing';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'Brand Partnership and Alliance Manager';
UPDATE designations SET department = 'Livecom' WHERE title = 'Asst . Manager MICE & Operations';
UPDATE designations SET department = 'Livecom' WHERE title = 'Asst. Manager Operations';
UPDATE designations SET department = 'Administrator' WHERE title = 'Sr. System Administration';
UPDATE designations SET department = 'Livecom' WHERE title = 'Sr. Executive - LiveCOM Operations';
UPDATE designations SET department = 'CSBD' WHERE title = 'Associate - Strategic Business Unit';
UPDATE designations SET department = 'CSBD' WHERE title = 'Sr. Business Manager';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Asst. Manager - DemandCOM';
UPDATE designations SET department = 'Digicom' WHERE title = 'Sr. Copy Writer';
UPDATE designations SET department = 'Administrator' WHERE title = 'Executive - HR & Admin';
UPDATE designations SET department = 'Digicom' WHERE title = 'Creative Director & Brand Communication';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Sr. Executive - Data Quality Assessment';
UPDATE designations SET department = 'CSBD' WHERE title = 'Account Manager';
UPDATE designations SET department = 'CommunityCOM' WHERE title = 'Executive - Marketing';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Sr. Manager - DemandCOM Operations';
UPDATE designations SET department = 'CSBD' WHERE title = 'Executive- Client Servicing';
UPDATE designations SET department = 'Digicom' WHERE title = 'Graphic Artist';
UPDATE designations SET department = 'Demandcom-Database' WHERE title = 'Team Leader Database';
UPDATE designations SET department = 'Demandcom-Calling' WHERE title = 'Quality Analyst';